---
- hosts: all
  tasks:
    - name: Copy pcap file from ControlNode
      fetch:
        src: /home/rio/Desktop/rio.pcap
        dest: /home/rio/hoa8.1/
        flat: yes

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Extract executable file
      command: tcpflow -r /home/rio/hoa8.1/rio.pcap -o /home/rio/hoa8.1
      args:
        creates: /home/rio/hoa8.1/executable.exe

    - name: Debug.exe file
      command: cat /home/rio/hoa8.1/report.xml
      register: cat_output
      changed_when: false
 
    - debug:
        var: cat_output.stdout_lines
